### ISSUE TITLE
Why don't you change the repository name?

### ISSUE THREAD

**Issue by ZeroOneDeveloper** [soup061222/soup061222#1]
If you change the repository name to your own GitHub name, the README.md content is fixed in the profile overview. For more information, please refer to the link below.
https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/managing-your-profile-readme

**Comment by slashe2** [comment]
아하 넵 알겠습니다 좋은 정보 주셔서 감사합니다!
Ah, Okay thank you very much!!
